### ISSUE TITLE
OnMessageReceived Does not use parameter "receivedMessage" in switch statement

### ISSUE THREAD

**Issue by emveor** [ls29322/SimpleUnityTCP#1]
The definition of `OnMessageReceived()` has a parameter of type String called receivedMessage, The function should use this parameter for the switch statement, but instead uses m_ReceivedMessage, 

Furthermore, `OnMessageReceived() `is only used once in the code, and it sends `m_ReceivedMessage` as the parameter anyways, making the parameter in the function definition redundant and unnecesary.

The code works as it is. but it would not work correctly if somebody, for example, was to simulate an incoming message by calling  `OnMessageReceived() `directly  ( I.E: `OnMessageReceived("Close") `will not close the client )

**Comment by EricBatlle** [comment]
Good catch @emveor , you're completly right. 

This project is like 2 years old and without updates ^^' I'll update it including your observation when I've enough time, thanks anyway!

**Comment by EricBatlle** [comment]
Fixed with the latest update https://github.com/EricBatlle/SimpleUnityTCP/commit/d62613d8e5faa4e3598ef188e443b175deaa93b6
